---

- name: Fetch Oracle JDK artefacts
  delegate_to: 127.0.0.1
  run_once: true
  block:

    - name: 'Create temp directory at {{ oraclejdk_dl_dir }} (127.0.0.1)'
      file:
        path:   '{{ oraclejdk_dl_dir }}'
        state:  directory

    - name: 'Download Oracle JDK to temp directory (127.0.0.1)'
      get_url:
        url:      '{{ oraclejdk_url }}'
        headers:  '{{ oraclejdk_cookie }}'
        checksum: '{{ oraclejdk_checksum }}'
        dest:     '{{ oraclejdk_dl_dir }}/{{ oraclejdk_name }}.tar.gz'

  tags:
    - oraclejdk
    - oraclejdk_download

