---

- name: 'Check if Oracle JDK is already installed at {{ oraclejdk_home }}'
  stat:
    path:   '{{ oraclejdk_home }}'
  register: java_home_check
  tags:
    - oraclejdk
    - oraclejdk_install


- name: Install Oracle JDK artefacts
  block:

    - name: Copy and extract JDK archive
      when: java_home_check.stat.exists == false
      block:

        - name: 'Create JDK base root directory at {{ oraclejdk_home }}'
          file:
            path:   '{{ oraclejdk_home }}'
            state:  directory

        - name: 'Extract JDK archive to {{ oraclejdk_home }}'
          unarchive:
            src:        '{{ oraclejdk_dl_artefact_path }}'
            dest:       '{{ oraclejdk_home }}'
            extra_opts: ['--strip-components=1']


    - name: Set JAVA_HOME
      when: oraclejdk_sethome
      block:

        - name: 'Create {{ oraclejdk_profile_file }} if it does not exist'
          copy:
            content:  ''
            dest:     '{{ oraclejdk_profile_file }}'
            force:    false

        - name: 'Set JAVA_HOME in {{ oraclejdk_profile_file  }} to {{ oraclejdk_home}}'
          lineinfile:
            path:     '{{ oraclejdk_profile_file }}'
            regexp:   '^export JAVA_HOME=.*'
            line:     'export JAVA_HOME={{ oraclejdk_home }}'

        - name: 'Add $JAVA_HOME/bin in {{ oraclejdk_profile_file }} to $PATH'
          lineinfile:
            path:     '{{ oraclejdk_profile_file }}'
            regexp:   '^export PATH=.*'
            line:     'export PATH=${PATH}:${JAVA_HOME}/bin'
   
    - name: Update alternatives
      when: oraclejdk_alternative_upd
      alternatives:
        name:     '{{ item }}'
        link:     '/usr/bin/{{ item }}'
        path:     '{{ oraclejdk_home }}/bin/{{ item }}'
        priority: '{{ oraclejdk_alternative_prio }}'
      with_items: '{{ oraclejdk_alternative_items }}'

  tags:    
    - oraclejdk
    - oraclejdk_install

