---

- name: Determine if JDK is v9+ based on folder layout
  stat:
    path:   '{{ oraclejdk_home }}/conf/security/java.security'
  register: jdk9_check


- name: Fetch Oracle Java Cryptography Extension (JCE) artefacts (JDK8 only)
  when: oraclejdk_jce_install and jdk9_check.stat.exists == false
  delegate_to: 127.0.0.1
  run_once: true
  block:

    - name: 'Create temp directory at {{ oraclejdk_dl_dir }} (JDK8 only) (127.0.0.1)'
      file:
        path:   '{{ oraclejdk_dl_dir }}'
        state:  directory

    - name: 'Download Oracle JCE to temp directory (JDK8 only) (127.0.0.1)'
      get_url:
        url:      '{{ oraclejdk_jce_url }}'
        headers:  '{{ oraclejdk_cookie }}'
        checksum: '{{ oraclejdk_jce_checksum }}'
        dest:     '{{ oraclejdk_dl_dir }}/{{ oraclejdk_jce_name }}.zip'

  tags:
    - oraclejdk
    - oraclejdk_jce
    - oraclejdk_jce_download


