---

- name: JCE block
  block:

  # JDK8
  - name: Install Oracle Java Cryptography Extension (JDK8 only)
    when: oraclejdk_jce_install and jce_installed.stdout == 'false' and jdk9_check.stat.exists == false
    copy:
      src:    '{{ oraclejdk_dl_dir }}/{{ oraclejdk_jce_name }}/{{ item }}'
      dest:   '{{ oraclejdk_home }}/jre/lib/security/{{ item }}'
    with_items:
      - US_export_policy.jar
      - local_policy.jar

  # JDK9
  - name: Enable unlimited Java Cryptography Extension key strength (JDK9 only)
    when: oraclejdk_jce_install and jce_installed.stdout == 'false' and jdk9_check.stat.exists == true
    lineinfile:
      path:   '{{ oraclejdk_home }}/conf/security/java.security'
      regexp: '^crypto.policy=limited$'
      line:   'crypto.policy=unlimited'


  # final check if JCE is installed/enabled (both JDK8 & JDK9)
  - name: Check if JCE has successfully been installed
    shell: '{{ oraclejdk_home }}/bin/jrunscript -e "print (javax.crypto.Cipher.getMaxAllowedKeyLength(\"SHA256\") > 128);"'
    changed_when: false
    ignore_errors: true
    register: jce_check

  - name: Fail if JCE installation was not successful
    when: jce_check.stdout == 'false'
    fail:
      msg:  JCE has not successfully been installed.

  tags:
    - oraclejdk
    - oraclejdk_jce
    - oraclejdk_jce_install


