---

- name: Install JDK
  when: oraclejdk_state == 'present'
  block:

  - name: Fail this role in case the Oracle JDK license has not been agreed on
    when: oraclejdk_license_accept != true
    fail:
      msg: "Please accept the Oracle JDK license first by setting 'oraclejdk_license_accept: true'"
    tags:
      - oraclejdk

  - include: 02_fetchjdk.yml
  - include: 04_installjdk.yml
  - include: 06_fetchjce.yml
  - include: 08_installjce.yml
  - include: 10_cleanup.yml



- name: Remove JDK
  when: oraclejdk_state == 'absent'
  block:

  - name: Only proceed when the lift of JDK locations is not empty
    assert:
      that:
        - '{{ (oraclejdk_home|default([]))|length > 0 }}'
      msg: oraclejdk_home must be of type list and have at least one entry
    tags:
      - oraclejdk

  - include: 102_removejdk.yml
    with_items: '{{ oraclejdk_home }}'
    loop_control:
      loop_var: jdkitem

