---

- name: Install JDK
  when: oraclejdk_state == 'present'
  block:

  - name: Fail this role in case the Oracle JDK license has not been agreed on
    when: oraclejdk_license_accept != true
    fail:
      msg: "Please accept the Oracle JDK license first by setting 'oraclejdk_license_accept: true'"
    tags:
      - oraclejdk

  - include: 02_fetchjdk.yml
  - include: 04_installjdk.yml
  - include: 06_fetchjce.yml
  - include: 08_installjce.yml
  - include: 10_cleanup.yml



- name: Remove JDK
  when: oraclejdk_state == 'absent'
  block:

    - name: Remove Java alternatives for this JDK
      command: 'update-alternatives --remove "{{ item }}" "{{ oraclejdk_home}}/bin/{{ item }}"'
      with_items: '{{ oraclejdk_alternative_items }}'
      changed_when: false

    - name: 'Check if {{ oraclejdk_profile_file }} exists'
      stat:
        path: '{{ oraclejdk_profile_file }}'
      register: profile_file_check

    - name: Remove JAVA_HOME if pointing to this JDK
      when: profile_file_check.stat.exists == true
      lineinfile:
        path:     '{{ oraclejdk_profile_file }}'
        regexp:   '^export JAVA_HOME={{ oraclejdk_home }}'
        line:     'export JAVA_HOME='
        backrefs: true
  
    - name: 'Remove JDK home directory at {{ oraclejdk_home }}'
      file:
        path: '{{ oraclejdk_home }}'
        state: absent



