---

- name: Fail this role in case the Oracle JDK license has not been agreed on
  when: oraclejdk_license_accept != true
  fail:
    msg: "Please accept the Oracle JDK license first by setting 'oraclejdk_license_accept: true'"
  tags:
    - oraclejdk

- include: 02_fetchjdk.yml
- include: 04_installjdk.yml
- include: 06_fetchjce.yml
- include: 08_installjce.yml
- include: 10_cleanup.yml


